package com.dc.sb.dubbo.provider.mapper;

import com.dc.sb.dubbo.provider.model.Ddd;
import org.apache.ibatis.annotations.Insert;

public interface DddMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddd
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ddd (id, smail_img, ",
        "goods_name, goods_desc)",
        "values (#{id,jdbcType=INTEGER}, #{smailImg,jdbcType=VARCHAR}, ",
        "#{goodsName,jdbcType=VARCHAR}, #{goodsDesc,jdbcType=VARCHAR})"
    })
    int insert(Ddd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddd
     *
     * @mbggenerated
     */
    int insertSelective(Ddd record);
}