package com.dc.sb.dubbo.provider.mapper;

import com.dc.sb.dubbo.provider.model.Demo1;
import org.apache.ibatis.annotations.Insert;

public interface Demo1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo1
     *
     * @mbggenerated
     */
    @Insert({
        "insert into demo1 (id, name, ",
        "input, desc)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{input,jdbcType=TIMESTAMP}, #{desc,jdbcType=VARCHAR})"
    })
    int insert(Demo1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo1
     *
     * @mbggenerated
     */
    int insertSelective(Demo1 record);
}