package com.dc.sb.dubbo.provider.mapper;

import com.dc.sb.dubbo.provider.model.TGoods;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_goods",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_goods (id, smail_img, ",
        "goods_name, goods_desc, ",
        "price, input_date, ",
        "update_date, status, ",
        "goods_type_id, goods_kc, ",
        "buy_xz_num)",
        "values (#{id,jdbcType=VARCHAR}, #{smailImg,jdbcType=VARCHAR}, ",
        "#{goodsName,jdbcType=VARCHAR}, #{goodsDesc,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{inputDate,jdbcType=TIMESTAMP}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{status,jdbcType=CHAR}, ",
        "#{goodsTypeId,jdbcType=VARCHAR}, #{goodsKc,jdbcType=INTEGER}, ",
        "#{buyXzNum,jdbcType=INTEGER})"
    })
    int insert(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int insertSelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, smail_img, goods_name, goods_desc, price, input_date, update_date, status, ",
        "goods_type_id, goods_kc, buy_xz_num",
        "from t_goods",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    TGoods selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    @Update({
        "update t_goods",
        "set smail_img = #{smailImg,jdbcType=VARCHAR},",
          "goods_name = #{goodsName,jdbcType=VARCHAR},",
          "goods_desc = #{goodsDesc,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "input_date = #{inputDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=CHAR},",
          "goods_type_id = #{goodsTypeId,jdbcType=VARCHAR},",
          "goods_kc = #{goodsKc,jdbcType=INTEGER},",
          "buy_xz_num = #{buyXzNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TGoods record);
}