package com.dc.sb.dubbo.provider.mapper;

import com.dc.sb.dubbo.provider.model.TPinpai;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface TPinpaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pinpai
     *
     * @mbggenerated
     */
    @Delete({
            "delete from t_pinpai",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pinpai
     *
     * @mbggenerated
     */
    @Insert({
            "insert into t_pinpai (id, pin_pai_name, ",
            "img_url)",
            "values (#{id,jdbcType=INTEGER}, #{pinPaiName,jdbcType=VARCHAR}, ",
            "#{imgUrl,jdbcType=VARCHAR})"
    })
    int insert(TPinpai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pinpai
     *
     * @mbggenerated
     */
    int insertSelective(TPinpai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pinpai
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id, pin_pai_name, img_url",
            "from t_pinpai",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TPinpai selectByPrimaryKey(Integer id);

    @Select({
            "select",
            "id, pin_pai_name, img_url",
            "from t_pinpai"
    })
    @ResultMap("BaseResultMap")
    List<TPinpai> findAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pinpai
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPinpai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pinpai
     *
     * @mbggenerated
     */
    @Update({
            "update t_pinpai",
            "set pin_pai_name = #{pinPaiName,jdbcType=VARCHAR},",
            "img_url = #{imgUrl,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPinpai record);
}